# Generated by Django 3.2 on 2023-04-16 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='conf_code',
            field=models.CharField(default=1, max_length=6, verbose_name='Код подтверждения'),
            preserve_default=False,
        ),
    ]
