# Generated by Django 3.2 on 2023-04-10 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0003_auto_20230410_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='author',
        ),
        migrations.RemoveField(
            model_name='review',
            name='title',
        ),
        migrations.RemoveField(
            model_name='title',
            name='rating',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
