# Generated by Django 3.2 on 2023-04-14 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0005_auto_20230412_2251'),
        ('titles', '0006_remove_title_rating'),
    ]

    operations = [
    ]
