# Generated by Django 3.2 on 2023-04-19 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_alter_title_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ('name', 'year')},
        ),
        migrations.RemoveField(
            model_name='title',
            name='rating',
        ),
    ]
